services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mydb
      MARIADB_USER: urilll
      MARIADB_PASSWORD: samporejois22
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      mariadb_net:
        ipv4_address: 172.20.0.2

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    networks:
      mariadb_net:
        ipv4_address: 172.20.0.3

volumes:
  mariadb_data:
    driver: local

networks:
  mariadb_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
